name: 'Dev Chart Retention'
description: 'This Action is designed to store GitHub or Leetcode chart data in JSON and SVG format, push it into public repostiory and make use for your own website or blog.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  REPOSITORY_TOKEN:
    description: 'GitHub token for pushing data to repository'
    required: true
  username_github:
    description: 'GitHub username for getting contribution chart data'
    required: true
  username_leetcode:
    description: 'Leetcode username for getting contribution chart data'
    required: true

outputs:
  run_at:
    description: 'Run time'
    value: ${{ steps.fetch-data.outputs.run_at }}

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Fetch data
      id: fetch-data
      run: python actions/fetcher.py
      shell: bash