name: Data Fetcher Action
on: [push]

jobs:
  job-crawler:
    runs-on: ubuntu-latest
    name: Run fetcher
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch data
        id: fetch-data
        uses: ./ # Uses an action in the root directory
        with:
          github_token_for_push: 123
          github_username: 'github_username'
          leetcode_username: 'leetcode_username'
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"